[kvm_hosts]
satellite.wrhammers-xxx.de ansible_user=root ansible_ssh_private_key_file=/home/wrenk/.ssh/hetzner_key

[all:vars]
iso_url=http://internal-mirror.lab.local/isos/rhel-9-x86_64-dvd.iso
iso_path=/home/lib/libvirt/images/rhel-9-x86_64-dvd.iso
iso_checksum=c0dd53b73406b85b40d6168d1748e605d71361b2992d282c408b7d7d2e1d2c80
hetzner_ip=136.243.44.117

[kvm_hosts:vars]
vm_name=satellite-server
vm_ram_mb=16384
vm_vcpus=4
vm_disk_size=750G
vm_disk_path=/home/lib/libvirt/images/satellite-lab.qcow2
os_variant=rhel9.0
network_name=default